spring:
  application:
    name: item-service
  cloud:
      config:
        override-none: true
  rabbitmq:
    host: 176.20.15.47
    port: 5672
    username: admin
    password: admin
    
server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
    
